version: '3.8'
services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "80:8080"
      - "50000:50000"
    networks:
      - bridge_net
    # volumes:
    #   - jenkins_home:/var/jenkins_home
    # environment:
    #   - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

# volumes:
#   jenkins_home:

networks:
  bridge_net:
    driver: bridge